version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpttoapi
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      ADMIN_PASSWORD: TotallySecurePassword
      # If the parameter API_REVERSE_PROXY is empty, the default request URL is https://chat.openai.com/backend-api/conversation, and the PUID is <NOT> equired.
      #PUID: xxx
    volumes:
      - ./access_tokens.json:/app/access_tokens.json
      - ./cookies.json:/app/cookies.json
      - ./accounts.txt:/app/accounts.txt
      - ./proxies.txt:/app/proxies.txt
      - ./harPool:/app/harPool
